name: get_x_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  flutter: 
    sdk: flutter
  lottie: ^2.6.0
  google_fonts: ^4.0.4
  flutter_slidable: ^3.0.0
  image_picker: ^1.0.4
  sqflite: ^2.3.0
  fan_floating_menu: ^0.0.1
  intl: ^0.18.1
  path: ^1.8.3
  get_storage: ^2.1.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

